-- AlterTable
ALTER TABLE `Mortgage` ADD COLUMN `educationalQualification` ENUM('ELEMENTARY_SCHOOL', 'MIDDLE_SCHOOL', 'HIGH_SCHOOL', 'COLLEGE', 'VOCATIONAL_SCHOOL', 'GRADUATE_SCHOOL', 'ONLINE_COURSES', 'PROFESSIONAL_DEVELOPMENT', 'HOMESCHOOLING', 'LIFELONG_LEARNING', 'SPECIALIZED_TRAINING_PROGRAMS', 'LANGUAGE_COURSES', 'CERTIFICATE_PROGRAMS', 'TRADE_SCHOOLS') NULL,
    ADD COLUMN `familyMembersInUae` INTEGER NULL DEFAULT 0,
    ADD COLUMN `favoriteCity` VARCHAR(255) NULL,
    ADD COLUMN `homeCountryAddress` VARCHAR(255) NULL,
    ADD COLUMN `maritalStatus` ENUM('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED') NULL,
    ADD COLUMN `uaeResidenceAddress` VARCHAR(255) NULL,
    ADD COLUMN `yearsInUae` INTEGER NULL DEFAULT 0,
    MODIFY `additionalDetail` VARCHAR(255) NULL,
    MODIFY `customerInformation` VARCHAR(255) NULL;

-- CreateTable
CREATE TABLE `Reference` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NULL,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NULL,
    `phone` VARCHAR(255) NOT NULL,
    `relationship` VARCHAR(255) NOT NULL,
    `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
