/*
  Warnings:

  - The values [APARTMENT_AND_UNIT,ACREAGE,BLOCK_OF_UNITS,HOUSE,LAND,BULK_UNIT] on the enum `Property_propertyCategory` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `Document` MODIFY `type` ENUM('PASSPORT_COPY', 'VISA_COPY', 'EMIRATES_ID', 'BANK_STATEMENT_6_MONTHS', 'BANK_STATEMENT_1_YEAR', 'SALARY_CERTIFICATE', 'TRADE_LICENSE', 'MEMORANDUM_WITH_AMENDMENTS', 'VAT_CERTIFICATE_RETURN_RECEIPTS', 'OFFICE_TENANCY_CONTRACT_UTILITY_BILL', 'COMPANY_PROFILE_WEBSITE', 'TITLE_DEED_COPY', 'TENANCY_CONTRACT_COPY', 'RENTAL_CHEQUE_COPY', 'BANK_STATEMENT_3_MONTHS_EQUIVALENT_AED_25000', 'PROOF_OF_RESIDENCE', 'PROOF_OF_INCOME', 'COMPANY_BANK_STATEMENT_6_MONTHS', 'OWNERSHIP_PROOF_MOBILE_NUMBER', 'MOBILE_BILL_COPY', 'REAL_ESTATE_LICENSE') NOT NULL;

-- AlterTable
ALTER TABLE `Property` ADD COLUMN `completionStatus` ENUM('READY_SECONDARY', 'OFF_PLAN_SECONDARY', 'READY_PRIMARY', 'OFF_PLAN_PRIMARY') NOT NULL DEFAULT 'OFF_PLAN_PRIMARY',
    ADD COLUMN `layoutType` VARCHAR(255) NULL,
    ADD COLUMN `serviceCharges` VARCHAR(255) NULL,
    MODIFY `propertyCategory` ENUM('APARTMENT', 'TOWNHOUSE', 'VILLA', 'DUPLEX', 'PENTHOUSE', 'RESIDENTIAL_LAND', 'VILLA_COMPOUND', 'RESIDENTIAL_FULL_BUILDING', 'BULK_UNITS', 'BUNGALOW', 'COMMERCIAL_BUILDING', 'COMMERCIAL_FLOOR', 'COMMERCIAL_VILLA', 'COMMERCIAL_PLOT', 'FACTORY', 'INDUSTRIAL_UNIT_FOR_SALE', 'INDUSTRIAL_LAND', 'MIXED_USED_SAND', 'OFFICE_FOR_SALE', 'RETAIL_FOR_SALE', 'SHOP', 'STAFF_ACCOMMODATION_FOR_SALE', 'WAREHOUSE', 'SELL_COMMERCIAL_LAND', 'OTHER') NULL;

-- AlterTable
ALTER TABLE `RequiredDocument` MODIFY `documentType` ENUM('PASSPORT_COPY', 'VISA_COPY', 'EMIRATES_ID', 'BANK_STATEMENT_6_MONTHS', 'BANK_STATEMENT_1_YEAR', 'SALARY_CERTIFICATE', 'TRADE_LICENSE', 'MEMORANDUM_WITH_AMENDMENTS', 'VAT_CERTIFICATE_RETURN_RECEIPTS', 'OFFICE_TENANCY_CONTRACT_UTILITY_BILL', 'COMPANY_PROFILE_WEBSITE', 'TITLE_DEED_COPY', 'TENANCY_CONTRACT_COPY', 'RENTAL_CHEQUE_COPY', 'BANK_STATEMENT_3_MONTHS_EQUIVALENT_AED_25000', 'PROOF_OF_RESIDENCE', 'PROOF_OF_INCOME', 'COMPANY_BANK_STATEMENT_6_MONTHS', 'OWNERSHIP_PROOF_MOBILE_NUMBER', 'MOBILE_BILL_COPY', 'REAL_ESTATE_LICENSE') NOT NULL;
