-- CreateTable
CREATE TABLE `RequiredDocument` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NULL,
    `documentType` ENUM('PASSPORT_COPY', 'VISA_COPY', 'EMIRATES_ID', 'BANK_STATEMENT_6_MONTHS', 'BANK_STATEMENT_1_YEAR', 'SALARY_CERTIFICATE', 'TRADE_LICENSE', 'MEMORANDUM_WITH_AMENDMENTS', 'VAT_CERTIFICATE_RETURN_RECEIPTS', 'OFFICE_TENANCY_CONTRACT_UTILITY_BILL', 'COMPANY_PROFILE_WEBSITE', 'TITLE_DEED_COPY', 'TENANCY_CONTRACT_COPY', 'RENTAL_CHEQUE_COPY', 'BANK_STATEMENT_3_MONTHS_EQUIVALENT_AED_25000', 'PROOF_OF_RESIDENCE', 'PROOF_OF_INCOME', 'COMPANY_BANK_STATEMENT_6_MONTHS', 'OWNERSHIP_PROOF_MOBILE_NUMBER') NOT NULL,
    `isMandatory` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(0) NOT NULL,
    `updatedAt` DATETIME(0) NOT NULL,
    `requirementId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Requirement` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NULL,
    `incomeProfile` ENUM('SALARIED', 'SELF_EMPLOYED', 'RENTAL_INCOME') NOT NULL,
    `residenceType` ENUM('UAE_NATIONAL', 'UAE_RESIDENT', 'NON_UAE_RESIDENT') NOT NULL,
    `createdAt` DATETIME(0) NOT NULL,
    `updatedAt` DATETIME(0) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Document` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(155) NOT NULL,
    `documentTypeId` INTEGER NOT NULL,
    `documentType` ENUM('PASSPORT_COPY', 'VISA_COPY', 'EMIRATES_ID', 'BANK_STATEMENT_6_MONTHS', 'BANK_STATEMENT_1_YEAR', 'SALARY_CERTIFICATE', 'TRADE_LICENSE', 'MEMORANDUM_WITH_AMENDMENTS', 'VAT_CERTIFICATE_RETURN_RECEIPTS', 'OFFICE_TENANCY_CONTRACT_UTILITY_BILL', 'COMPANY_PROFILE_WEBSITE', 'TITLE_DEED_COPY', 'TENANCY_CONTRACT_COPY', 'RENTAL_CHEQUE_COPY', 'BANK_STATEMENT_3_MONTHS_EQUIVALENT_AED_25000', 'PROOF_OF_RESIDENCE', 'PROOF_OF_INCOME', 'COMPANY_BANK_STATEMENT_6_MONTHS', 'OWNERSHIP_PROOF_MOBILE_NUMBER') NOT NULL,
    `isMandatory` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(0) NOT NULL,
    `updatedAt` DATETIME(0) NOT NULL,
    `mortgageId` INTEGER NULL,
    `commentId` INTEGER NULL,

    UNIQUE INDEX `name`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Mortgage` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `firstName` VARCHAR(255) NOT NULL,
    `lastName` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `phoneNumber` VARCHAR(255) NULL,
    `dateOfBirth` DATETIME(0) NOT NULL,
    `intendedProperty` VARCHAR(255) NOT NULL,
    `monthlyIncome` DOUBLE NOT NULL,
    `createdAt` DATETIME(0) NOT NULL,
    `updatedAt` DATETIME(0) NOT NULL,
    `dialCode` VARCHAR(255) NULL,
    `country` VARCHAR(255) NULL DEFAULT '',
    `status` ENUM('SUBMITTED', 'UNDER_DOCUMENTATION_STAGE', 'SUBMITTED_TO_BANK', 'APPROVED', 'VALUATION_STAGE', 'FINAL_OFFER_LETTER', 'CASE_DISBURSED', 'PROPERTY_TRANSFER', 'TRANSACTION_COMPLETED', 'CASE_CLOSED', 'CASE_DECLINED') NOT NULL,
    `residenceType` ENUM('UAE_NATIONAL', 'UAE_RESIDENT', 'NON_UAE_RESIDENT') NOT NULL,
    `incomeProfile` ENUM('SALARIED', 'SELF_EMPLOYED', 'RENTAL_INCOME') NOT NULL,
    `loanType` ENUM('BUY_PROPERTY_FROM_SELLER', 'BUY_PROPERTY_FROM_DEVELOPER', 'SHIFT_PROPERTY_LOAN', 'GET_CASH_AGAINST_EXISTING_PROPERTY') NOT NULL,
    `userId` INTEGER NULL,

    INDEX `Mortgages_userId_foreign_idx`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MortgageTransaction` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `additionalDetail` TEXT NULL,
    `customerInformation` TEXT NULL,
    `createdAt` DATETIME(0) NOT NULL,
    `updatedAt` DATETIME(0) NOT NULL,
    `financeType` ENUM('ISLAMIC', 'CONVENTIONAL') NULL,
    `emirate` ENUM('DUBAI', 'ABU_DHABI', 'RAS_AL_KHAIMAH', 'SHARJAH', 'FUJAIRAH', 'AJMAN', 'UMM_AL_QUWAIN') NULL,
    `propertyType` ENUM('RESIDENTIAL', 'COMMERCIAL') NULL,
    `completionStatus` ENUM('COMPLETED', 'UNDER_CONSTRUCTION') NULL,
    `loanType` ENUM('BUY_PROPERTY_FROM_SELLER', 'BUY_PROPERTY_FROM_DEVELOPER', 'SHIFT_PROPERTY_LOAN', 'GET_CASH_AGAINST_EXISTING_PROPERTY') NULL,
    `mortgageId` INTEGER NOT NULL,

    INDEX `MortgageTransactions_mortgageId_foreign_idx`(`mortgageId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Comment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `mortgageId` INTEGER NOT NULL,
    `message` TEXT NOT NULL,
    `createdAt` DATETIME(0) NOT NULL,
    `updatedAt` DATETIME(0) NOT NULL,

    INDEX `mortgageId`(`mortgageId`),
    INDEX `userId`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `firstName` VARCHAR(255) NOT NULL,
    `lastName` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(0) NOT NULL,
    `role` ENUM('admin', 'advertiser', 'agent') NULL DEFAULT 'advertiser',
    `isEmailConfirmed` BOOLEAN NULL,

    UNIQUE INDEX `email`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `RequiredDocument` ADD CONSTRAINT `RequiredDocument_requirementId_fkey` FOREIGN KEY (`requirementId`) REFERENCES `Requirement`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Document` ADD CONSTRAINT `Document_mortgageId_fkey` FOREIGN KEY (`mortgageId`) REFERENCES `Mortgage`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Mortgage` ADD CONSTRAINT `mortgage_userId_foreign_idx` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `MortgageTransaction` ADD CONSTRAINT `MortgageTransactions_mortgageId_foreign_idx` FOREIGN KEY (`mortgageId`) REFERENCES `Mortgage`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `Comment` ADD CONSTRAINT `Comment_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Comment` ADD CONSTRAINT `MortgageComments_ibfk_2` FOREIGN KEY (`mortgageId`) REFERENCES `Mortgage`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

