-- AlterTable
ALTER TABLE `Property` ADD COLUMN `completionStatus` ENUM('READY_SECONDARY', 'OFF_PLAN_SECONDARY', 'READY_PRIMARY', 'OFF_PLAN_PRIMARY') NOT NULL DEFAULT 'OFF_PLAN_PRIMARY',
    ADD COLUMN `layoutType` VARCHAR(255) NULL,
    ADD COLUMN `serviceCharges` VARCHAR(255) NULL;
